### ISSUE TITLE
 app crashed

### ISSUE THREAD

**Issue by zozito** [dickwolff/DEGIRO-to-Ghostfolio#4]
Hi 

When I do the command  _npm run start_ the app starts but immediately I got the error _immediately_

Please find below all the output 

```
C:\Users\brito\Downloads\DEGIRO-to-Ghostfolio-main> npm run start

> degiro-to-ghostfolio@1.0.0 start
> nodemon

[nodemon] 3.0.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src\**\*
[nodemon] watching extensions: ts,js
[nodemon] starting `ts-node ./src/index.ts`
Read CSV file Account.csv. Start processing..
FetchError: invalid json response body at http://192.168.1.172:2000/?origin=host&app=ghostfolio&path=%2Fapi%2Fv1%2Fauth%2Fanonymous%2Fd85ab44361c6925eebe0bceacabc525e19b9533a37ea57cec5852076881a5879a824e1f9b119dc8ee3e100a82b62c7cf9f7754920c41e129271a93a8c0a45fb0 reason: Unexpected token < in JSON at position 0
    at C:\Users\brito\Downloads\DEGIRO-to-Ghostfolio-main\node_modules\node-fetch\lib\index.js:273:32
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'invalid-json
}
[nodemon] app crashed - waiting for file changes before starting...
```

I'm doing something wrong?

Thank you

**Comment by dickwolff** [comment]
Hi,

With the info above it looks like the authentication call to  Ghostfolio is not working right. When I check my own URL it looks something like `http://192.168.1.50:3333/api/v1/auth/anonymous/xxxxxxxxxxxx`. What did you put in the environment variable `GHOSTFOLIO_API_URL`?

**Comment by zozito** [comment]
Hi,

I put my token, if I follow the URL in a browser I get something like this

```
{
"authToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM1ZmFhYTg1LTk5MGEtNGEyZi1iNjEzLTZlNzE1MTVhNWQ3NiIsImlhdCI6MTY5MzkyNjUzOSwiZXhwIjoxNzA5NDc4NTM5fQ.XDVZw0_vveB8BuYSro8z-h23Rb6p8cz4c8fT1bxTUEk"
}
```

**Comment by zozito** [comment]
Hi,

You do have any advise for me?

Thank you

**Comment by dickwolff** [comment]
Please check the new version of the tool. I have moved it to another repo (merging it with my other Trading 212 exporter). I have a pre-build which now also retrieves data directly from Yahoo Finance, since Ghostflio made some changes in 2.0+ which made the tool very slow. This change removes your problem since the tool no longer uses Ghostfolio for data retrieval.

Check it [here](https://github.com/dickwolff/Export-To-Ghostfolio/tree/feature/Retrieve-From-Yahoo-Finance)
